version: "2"
services:
  webapp:
    container_name: pagecarton
    image: pagecarton
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./pagecarton/core/local_html:/var/www/html
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
